/*
 * drift_calc.c
 * Patrick Alken
 *
 * This module contains routines related to computing the
 * drift model for given parameter values. The model
 * coefficients must first be generated by the 'drift' program.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <errno.h>

#include <gsl/gsl_vector.h>
#include <gsl/gsl_math.h>
#include "ndlinear/gsl_multifit_ndlinear.h"

#include "drift_basis.h"
#include "drift_calc.h"
#include "drift_files.h"

static size_t read_coeffs(const char *filename, gsl_vector *x);

/*
drift_calc_alloc()
  Allocate a workspace for computing the model
*/

drift_calc_workspace *
drift_calc_alloc()
{
  drift_calc_workspace *w;
  size_t N[N_DRIFT_FIT];

  w = (drift_calc_workspace *) calloc(1, sizeof(drift_calc_workspace));
  if (!w)
    return 0;

  N[IDX_DRIFT_T] = N_DRIFT_SUM_DEFAULT_T;
  N[IDX_DRIFT_S] = N_DRIFT_SUM_DEFAULT_S;
  N[IDX_DRIFT_EUVAC] = N_DRIFT_SUM_DEFAULT_EUVAC;

  w->u[IDX_DRIFT_T] = &get_drift_basis_t;
  w->u[IDX_DRIFT_S] = &get_drift_basis_s;
  w->u[IDX_DRIFT_EUVAC] = &get_drift_basis_euvac;

  w->drift_basis_workspace_p = drift_basis_alloc(N);
  if (!w->drift_basis_workspace_p)
    {
      drift_calc_free(w);
      return 0;
    }

  w->ndlinear_p = gsl_multifit_ndlinear_alloc(N_DRIFT_FIT,
                                              N,
                                              w->u,
                                              w->drift_basis_workspace_p);
  if (!w->ndlinear_p)
    {
      drift_calc_free(w);
      return 0;
    }

  w->mean_coeffs = gsl_vector_alloc(w->ndlinear_p->n_coeffs);
  w->stddev_coeffs = gsl_vector_alloc(w->ndlinear_p->n_coeffs);
  if (!w->mean_coeffs || !w->stddev_coeffs)
    {
      drift_calc_free(w);
      return 0;
    }

  /* the files are opened relative to the current directory (the python wrapper changes into the package's
     data directory first); a missing or short file must not silently give an all-zero model */
  if (read_coeffs(FILE_DRIFT_MEAN, w->mean_coeffs) != w->mean_coeffs->size ||
      read_coeffs(FILE_DRIFT_STDDEV, w->stddev_coeffs) != w->stddev_coeffs->size)
    {
      drift_calc_free(w);
      return 0;
    }

  return (w);
} /* drift_calc_alloc() */

/*
drift_calc_free()
  Free workspace w
*/

void
drift_calc_free(drift_calc_workspace *w)
{
  if (!w)
    return;

  if (w->ndlinear_p)
    gsl_multifit_ndlinear_free(w->ndlinear_p);

  if (w->drift_basis_workspace_p)
    drift_basis_free(w->drift_basis_workspace_p);

  if (w->mean_coeffs)
    gsl_vector_free(w->mean_coeffs);

  if (w->stddev_coeffs)
    gsl_vector_free(w->stddev_coeffs);

  free(w);
} /* drift_calc_free() */

/*
drift_calc_mean()
  Calculate the drift velocity mean for given parameters

Inputs: t   - local time (hours)
        s   - season (day of year 0 - 365)
        p   - EUVAC value (F10.7 + F10.7A) / 2
        w   - workspace

Return: v(t, s, p) in units of m/s
*/

double
drift_calc_mean(double t, double s, double p, drift_calc_workspace *w)
{
  double v;
  double x[N_DRIFT_FIT];
  gsl_vector_view xv = gsl_vector_view_array(x, N_DRIFT_FIT);

  if (t < DRIFT_LT_MIN || t > DRIFT_LT_MAX)
    {
      fprintf(stderr, "drift_calc_mean: error: t[%f] outside of LT interval\n",
              t);
      return (0.0); /* t outside of interval */
    }

  x[IDX_DRIFT_T] = t;
  x[IDX_DRIFT_S] = s;
  x[IDX_DRIFT_EUVAC] = p;

  v = gsl_multifit_ndlinear_calc(&xv.vector, w->mean_coeffs,
                                 w->ndlinear_p);

  return v;
} /* drift_calc_mean() */

/*
drift_calc_stddev()
  Calculate the drift velocity standard deviation for given parameters

Inputs: t   - local time (hours)
        s   - season (day of year 0 - 365)
        p   - EUVAC value (F10.7 + F10.7A) / 2
        w   - workspace

Return: sigma(t, s, p) in units of m/s
*/

double
drift_calc_stddev(double t, double s, double p, drift_calc_workspace *w)
{
  double sigma;
  double x[N_DRIFT_FIT];
  gsl_vector_view xv = gsl_vector_view_array(x, N_DRIFT_FIT);

  if (t < DRIFT_LT_MIN || t > DRIFT_LT_MAX)
    {
      fprintf(stderr, "drift_calc_stddev: error: t[%f] outside of LT interval\n",
              t);
      return (0.0); /* t outside of interval */
    }

  x[IDX_DRIFT_T] = t;
  x[IDX_DRIFT_S] = s;
  x[IDX_DRIFT_EUVAC] = p;

  sigma = gsl_multifit_ndlinear_calc(&xv.vector, w->stddev_coeffs,
                                     w->ndlinear_p);

  return (fabs(sigma));
} /* drift_calc_stddev() */

#define MAX_BUF  1000

/*
read_coeffs()
  Read the coefficients in 'filename' and store them in 'x'
*/

static size_t
read_coeffs(const char *filename, gsl_vector *x)
{
  FILE *fp;
  size_t cnt;
  char buf[MAX_BUF];
  int n;
  double y;

  fp = fopen(filename, "r");
  if (!fp)
    {
      fprintf(stderr, "Unable to open %s\n", filename);
      perror("fopen");
      return 0;
    }

  cnt = 0;
  while (fgets(buf, MAX_BUF, fp) != NULL)
    {
      if (*buf == '#')
        continue;

      n = sscanf(buf, "%le\n", &y);
      if (n <= 0)
        continue;

      gsl_vector_set(x, cnt++, y);
    }

  fclose(fp);

  return (cnt);
} /* read_coeffs() */
