#define FILE_DRIFT_MEAN             "drift_mean_coeffs"
#define FILE_DRIFT_STDDEV           "drift_stddev_coeffs"
#define FILE_MODEL_PHI_OUT          "plot_phi_data.txt"
#define FILE_MODEL_T_OUT            "plot_t_data1.txt"
#define FILE_MODEL_S_OUT            "plot_s_data.txt"
#define FILE_MODEL_EUVAC_OUT        "plot_euvac_data.txt"
